import * as Svgicons from '@/navigation/menusvg-icons.js'

export default [
  // {
  //   path: '/',
  //   title: 'Dashboard',
  //   icon: Svgicons.Dashboardicon,
  //   type: 'link',
  //   active: false,
  //   dirchange: false,
  //   action: 'read',
  //   subject: 'Dashboard',
  // },
  // {
  //   path: '/second-page',
  //   title: 'Second Page',
  //   icon: Svgicons.Dashboardicon,
  //   type: 'link',
  //   active: false,
  //   dirchange: false,
  //   action: 'read',
  //   subject: 'Second Page',
  // },
  {
    path: '/mar-dashboard-page',
    title: 'Dashboard MAR',
    icon: Svgicons.Dashboardicon,
    type: 'link',
    active: false,
    dirchange: false,
    action: 'read',
    subject: 'Dashboard MAR',
  },
  {
    path: '/mar-monitoring-page',
    title: 'Monitoring MAR',
    icon: Svgicons.Dashboardicon,
    type: 'link',
    active: false,
    dirchange: false,
    action: 'read',
    subject: 'Monitoring MAR',
  },
  // {
  //   icon: Svgicons.Pagesicon,
  //   title: 'Pages',
  //   type: 'sub',
  //   active: false,
  //   dirchange: false,
  //   children: [
  //     {
  //       icon: Svgicons.Erroricon,
  //       title: 'Error',
  //       type: 'sub',
  //       active: false,
  //       selected: false,
  //       dirchange: false,
  //       children: [
  //         {
  //           path: '/third-page',
  //           type: 'link',
  //           active: false,
  //           selected: false,
  //           dirchange: false,
  //           title: 'Third Page',
  //           action: 'read',
  //           subject: 'Third Page',
  //         },
  //         {
  //           path: '/fourth-page',
  //           type: 'link',
  //           active: false,
  //           selected: false,
  //           dirchange: false,
  //           title: 'Fourth Page',
  //           action: 'read',
  //           subject: 'Fourth Page',
  //         },
  //       ],
  //     },
  //   ],
  // },
]
